# TOMCAT SERVER

server:
  port: 8080

#JPA
spring:
 jpa:
   hibernate:
     ddl-auto: update
   properties:
     hibernate:
       dialect: org.hibernate.dialect.MySQL5Dialect

#Datasource
 datasource:
   url: jdbc:mysql://localhost:8889/ciceT612?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
   username: root
   password: root

